export const connections = [
    {
      id: "alice1",
      name: "Alice Johnson",
      position: "CEO",
      company: "TechCorp",
      skills: ["Leadership", "Business Strategy", "AI Solutions"],
      country: "USA",
      image: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    {
      id: "bob1",
      name: "Bob Smith",
      position: "Marketing Head",
      company: "BizSolutions",
      skills: ["Digital Marketing", "SEO", "Branding"],
      country: "UK",
      image: "https://randomuser.me/api/portraits/men/35.jpg",
    },
    {
      id: "charlie1",
      name: "Charlie Brown",
      position: "Product Manager",
      company: "InnovateX",
      skills: ["Product Design", "Agile", "UI/UX"],
      country: "Australia",
      image: "https://randomuser.me/api/portraits/men/76.jpg",
    },
    {
      id: "priya1",
      name: "Priya Kapoor",
      position: "Software Engineer",
      company: "CodeSphere",
      skills: ["React", "Node.js", "GraphQL"],
      country: "India",
      image: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    {
      id: "lucas1",
      name: "Lucas Martins",
      position: "Data Scientist",
      company: "DataVision",
      skills: ["Machine Learning", "Python", "Data Analytics"],
      country: "Brazil",
      image: "https://randomuser.me/api/portraits/men/88.jpg",
    },
    {
      id: "yuki1",
      name: "Yuki Tanaka",
      position: "UI Designer",
      company: "PixelPerfect",
      skills: ["Figma", "Adobe XD", "Illustration"],
      country: "Japan",
      image: "https://randomuser.me/api/portraits/women/15.jpg",
    },
  ];