const jobsData = {
  recent: [
    {
      title: "Frontend Developer Intern",
      company: "TechNova",
      location: "Remote",
      logo: "https://cdn-icons-png.flaticon.com/512/5968/5968292.png",
      type: "Internship",
      salary: "$15/hr",
      skills: ["HTML", "CSS", "JavaScript"],
    },
    {
      title: "Junior Backend Developer",
      company: "DataForge",
      location: "Austin, TX",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919825.png",
      type: "Full-time",
      salary: "$50k - $65k",
      skills: ["Node.js", "Express", "MongoDB"],
    },
    {
      title: "Mid-Level DevOps Engineer",
      company: "CloudCore",
      location: "Remote",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919839.png",
      type: "Full-time",
      salary: "$85k - $105k",
      skills: ["AWS", "Docker", "Kubernetes"],
    },
    {
      title: "UI/UX Designer",
      company: "PixelPerfect",
      location: "Remote",
      logo: "https://cdn-icons-png.flaticon.com/512/888/888879.png",
      type: "Contract",
      salary: "$45/hr",
      skills: ["Figma", "Adobe XD", "User Research"],
    },
    {
      title: "Senior Full Stack Engineer",
      company: "Innovatech",
      location: "San Francisco, CA",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919832.png",
      type: "Full-time",
      salary: "$120k - $150k",
      skills: ["React", "Node.js", "GraphQL"],
    },
    {
      title: "Software Tester",
      company: "BugBusters",
      location: "Chicago, IL",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919842.png",
      type: "Full-time",
      salary: "$55k - $70k",
      skills: ["Selenium", "Cypress", "Manual Testing"],
    },
  ],
  like: [
    {
      title: "React Developer",
      company: "ByteBuilders",
      location: "Remote",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919831.png",
      type: "Full-time",
      salary: "$65k - $85k",
      skills: ["React", "Redux", "Tailwind"],
    },
    {
      title: "Cloud Solutions Architect",
      company: "SkyNet Solutions",
      location: "San Francisco, CA",
      logo: "https://cdn-icons-png.flaticon.com/512/888/888859.png",
      type: "Full-time",
      salary: "$120k - $150k",
      skills: ["AWS", "Azure", "Kubernetes"],
    },
    {
      title: "Junior Mobile App Developer",
      company: "Appify",
      location: "Remote",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919852.png",
      type: "Full-time",
      salary: "$55k - $70k",
      skills: ["Flutter", "React Native"],
    },
    {
      title: "Cybersecurity Analyst",
      company: "SafeNet",
      location: "Boston, MA",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919833.png",
      type: "Full-time",
      salary: "$80k - $100k",
      skills: ["Network Security", "Penetration Testing", "SIEM"],
    },
    {
      title: "Junior Data Analyst",
      company: "InsightIQ",
      location: "Remote",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919830.png",
      type: "Full-time",
      salary: "$50k - $65k",
      skills: ["Excel", "SQL", "Tableau"],
    },
    {
      title: "AI Engineer",
      company: "NeuroNet",
      location: "Seattle, WA",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919827.png",
      type: "Full-time",
      salary: "$110k - $140k",
      skills: ["Python", "TensorFlow", "Machine Learning"],
    },
  ],
  local: [
    {
      title: "IT Support Specialist",
      company: "CityTech",
      location: "Nearby",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919829.png",
      type: "Full-time",
      salary: "$40k - $55k",
      skills: ["Troubleshooting", "Networking"],
    },
    {
      title: "Junior Web Developer",
      company: "LocalWebs",
      location: "Nearby",
      logo: "https://cdn-icons-png.flaticon.com/512/888/888875.png",
      type: "Full-time",
      salary: "$45k - $60k",
      skills: ["HTML", "CSS", "JavaScript"],
    },
    {
      title: "IT Intern",
      company: "Metro IT Solutions",
      location: "Nearby",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919846.png",
      type: "Internship",
      salary: "$12/hr",
      skills: ["Basic Networking", "Microsoft Office"],
    },
    {
      title: "Systems Administrator",
      company: "DataGuard",
      location: "Nearby",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919828.png",
      type: "Full-time",
      salary: "$75k - $90k",
      skills: ["Linux", "Windows Server", "Cloud Platforms"],
    },
    {
      title: "Technical Writer",
      company: "DocuTech",
      location: "Nearby",
      logo: "https://cdn-icons-png.flaticon.com/512/888/888858.png",
      type: "Contract",
      salary: "$30/hr",
      skills: ["Technical Writing", "API Documentation"],
    },
    {
      title: "Network Engineer",
      company: "FiberFast",
      location: "Nearby",
      logo: "https://cdn-icons-png.flaticon.com/512/919/919844.png",
      type: "Full-time",
      salary: "$85k - $105k",
      skills: ["Cisco", "Routing", "Switching"],
    },
  ],
};
export default jobsData;
